### ISSUE TITLE
MAP64 floating platforms break easily

### ISSUE THREAD

**Issue by AlexWFreitas** [Hypnotoad90/jumpmaze-zan#1]
Near the end you can glitch the elevator by putting a player on top of it and a player below it at the same time.

https://www.youtube.com/watch?v=wWUMdIzjBuc

**Comment by PlusGit** [comment]
made the title more detailed u lazy bastard

**Comment by AlexWFreitas** [comment]
Actually I think you only need a player below the elevator blocking the path.

I saw a guy break it alone by himself.

**Comment by Hypnotoad90** [comment]
Should be fixed
