### ISSUE TITLE
Map28 / Map29 music too loud.

### ISSUE THREAD

**Issue by AlexWFreitas** [Hypnotoad90/jumpmaze-zan#11]
Cloud 9 and  Volcano Hallway have musics that are way louder than the other maps.

**Comment by AlexWFreitas** [comment]
Test this to replace Map29 music.
[D_VOLCAN.zip](https://github.com/Hypnotoad90/jumpmaze-zan/files/139959/D_VOLCAN.zip)

**Comment by Hypnotoad90** [comment]
Fixed
