### ISSUE TITLE
autistic ticket by autistic man

### ISSUE THREAD

**Issue by AlexWFreitas** [Hypnotoad90/jumpmaze-zan#15]
If you have at least 2 players in a server ingame, if you call the Puke commands for Restart Map / Next Map then enter Spectator as soon as you send the Puke Votes, the Puke Vote System freezes and can't be called anymore.

**Comment by Wirtualnosc** [comment]
Fixed with https://github.com/Hypnotoad90/jumpmaze-zan/commit/e6765d49c92935bf9b5951cea81ea0682a7d58c6
