### ISSUE TITLE
Map61 Asymmetry.

### ISSUE THREAD

**Issue by AlexWFreitas** [Hypnotoad90/jumpmaze-zan#2]
On Map61, there is a problem where one of the platforms is too far from the walls unlike the other side. This makes it easier to do mistakes when jumping on that part.

http://i.imgur.com/zepn89K.png

http://i.imgur.com/plqfQ1L.png

**Comment by AlexWFreitas** [comment]
Left path :
http://i.imgur.com/lFIgxwU.jpg

http://i.imgur.com/48GsnMb.png

Right path :

http://i.imgur.com/tRD0eoz.jpg

http://i.imgur.com/WD4tIoJ.jpg

**Comment by Hypnotoad90** [comment]
Note to self: set both as being close to the wall

**Comment by Hypnotoad90** [comment]
Should be fixed here: https://github.com/Hypnotoad90/jumpmaze-zan/commit/add18176f8f05117a7a5a60e721e77a051418bde
