### ISSUE TITLE
Discord report by Snail489#0666: hypnotoad is gay

### ISSUE THREAD

**Issue by FirestickJimmothy** [Hypnotoad90/jumpmaze-zan#36]
[__Snail489#0666 posted in Jumpmaze #bot-shit:__](https://discordapp.com/channels/481500102557564968/580457152959873028/798856002556264468)

> hypnotoad is gay

**Comment by thenaonao** [comment]
Guys, I think we need to reopen this ticket. 
It clearly holds some truth to the matter.
